version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data_container:/data/db
      - ./initdb:/docker-entrypoint-initdb.d #scripts sql docker
    networks:
      - keycloak_network

  redis:
    image: redis:4
    container_name: redis-rasplus-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data/redis

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: KEYCLOAK
      DB_USER: rasmoo
      DB_PASSWORD: senha123
    depends_on:
      - mysql
    volumes:
      - keycloak_data_container:/opt/jboss/keycloak/standalone/data
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  mysql_data_container:
  redis_data_container:
  keycloak_data_container:
